SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS "chatwebappserver" DEFAULT CHARACTER SET latin1 ;
USE "chatwebappserver" ;

CREATE TABLE IF NOT EXISTS `chatwebappserver`.`user` (
  `user_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `log_status` BIT(1) NULL DEFAULT NULL,
  `nick` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `status_txt` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


CREATE TABLE IF NOT EXISTS `chatwebappserver`.`message` (
  `message_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `message_date` DATETIME NULL DEFAULT NULL,
  `message_status` INT(11) NULL DEFAULT NULL,
  `recipient` BIGINT(20) NULL DEFAULT NULL,
  `sender` BIGINT(20) NULL DEFAULT NULL,
  `message_text` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`message_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;